apiVersion: shipa.crossplane.io/v1alpha1
kind: AppDeploy
metadata:
  name: deploy-of-some-application
spec:
  forProvider:
    app: crossplane-deployed-app
    image: "docker.io/shipasoftware/bulletinboard:1.0"
    steps: 2
    step-weight: 1
    step_interval: 1m

#other images
# ghcr.io/podtato-head/podtatoserver:v0.1.1
# docker.io/wordpress
# docker.io/shipasoftware/bulletinboard:1.0
